import gradio as gr
from planqk.service.client import PlanqkServiceClient

## Subscribe to the service https://platform.planqk.de/marketplace/apis/88b46e18-3d5f-4674-ba04-0d3416c0decd and add your application credentials
consumer_key = ""
consumer_secret = ""
service_endpoint = "https://gateway.platform.planqk.de/anaqor/quantum-random-number-generator/1.0.0"


title = "A Gradio Demo Example!!"
description = "This Demo is calling the [Quantum Random Number Generator](https://platform.planqk.de/marketplace/apis/88b46e18-3d5f-4674-ba04-0d3416c0decd). To try it out create an Application and subscribe to the service."


def run(n_numbers: int):
    client = PlanqkServiceClient(service_endpoint, consumer_key, consumer_secret)
    data = {"n_numbers": n_numbers}
    params = {"n_bits": 4, "backend": "qasm_simulator"}
    job = client.start_execution(data=data, params=params)
    result = client.get_result(job.id)

    random_number_list = result["result"]["random_number_list"]
    return ", ".join([str(x) for x in random_number_list])


demo = gr.Interface(
    run,
    gr.Number(label="The amount of numbers be generated", value=10),
    gr.Text(
        label="The random numbers generated by the Quantum Random Number Generator",
    ),
    examples=[1, 2, 3, 4, 5],
    title=title,
    description=description,
    allow_flagging="never",
)

demo.launch()
